server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: create-drop

block:
  size: 4096
  replicas: 2

