eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8764

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  application:
    name: datanode3
